/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as PublicSignUpSplatRouteImport } from './routes/_public/sign-up.$'
import { Route as PublicSignInSplatRouteImport } from './routes/_public/sign-in.$'
import { Route as PubliclegalTermsRouteImport } from './routes/_public/(legal)/terms'
import { Route as PubliclegalSupportRouteImport } from './routes/_public/(legal)/support'
import { Route as PubliclegalPrivacyRouteImport } from './routes/_public/(legal)/privacy'
import { Route as ProtectedListsListIdRouteImport } from './routes/_protected/lists.$listId'

const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignUpSplatRoute = PublicSignUpSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicSignUpRoute,
} as any)
const PublicSignInSplatRoute = PublicSignInSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicSignInRoute,
} as any)
const PubliclegalTermsRoute = PubliclegalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PubliclegalSupportRoute = PubliclegalSupportRouteImport.update({
  id: '/(legal)/support',
  path: '/support',
  getParentRoute: () => PublicRoute,
} as any)
const PubliclegalPrivacyRoute = PubliclegalPrivacyRouteImport.update({
  id: '/(legal)/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedListsListIdRoute = ProtectedListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscription': typeof SubscriptionRoute
  '/sign-in': typeof PublicSignInRouteWithChildren
  '/sign-up': typeof PublicSignUpRouteWithChildren
  '/lists/$listId': typeof ProtectedListsListIdRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/support': typeof PubliclegalSupportRoute
  '/terms': typeof PubliclegalTermsRoute
  '/sign-in/$': typeof PublicSignInSplatRoute
  '/sign-up/$': typeof PublicSignUpSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscription': typeof SubscriptionRoute
  '/sign-in': typeof PublicSignInRouteWithChildren
  '/sign-up': typeof PublicSignUpRouteWithChildren
  '/lists/$listId': typeof ProtectedListsListIdRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/support': typeof PubliclegalSupportRoute
  '/terms': typeof PubliclegalTermsRoute
  '/sign-in/$': typeof PublicSignInSplatRoute
  '/sign-up/$': typeof PublicSignUpSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/subscription': typeof SubscriptionRoute
  '/_public/sign-in': typeof PublicSignInRouteWithChildren
  '/_public/sign-up': typeof PublicSignUpRouteWithChildren
  '/_protected/lists/$listId': typeof ProtectedListsListIdRoute
  '/_public/(legal)/privacy': typeof PubliclegalPrivacyRoute
  '/_public/(legal)/support': typeof PubliclegalSupportRoute
  '/_public/(legal)/terms': typeof PubliclegalTermsRoute
  '/_public/sign-in/$': typeof PublicSignInSplatRoute
  '/_public/sign-up/$': typeof PublicSignUpSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subscription'
    | '/sign-in'
    | '/sign-up'
    | '/lists/$listId'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/sign-in/$'
    | '/sign-up/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscription'
    | '/sign-in'
    | '/sign-up'
    | '/lists/$listId'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/sign-in/$'
    | '/sign-up/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/subscription'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_protected/lists/$listId'
    | '/_public/(legal)/privacy'
    | '/_public/(legal)/support'
    | '/_public/(legal)/terms'
    | '/_public/sign-in/$'
    | '/_public/sign-up/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  SubscriptionRoute: typeof SubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-up/$': {
      id: '/_public/sign-up/$'
      path: '/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof PublicSignUpSplatRouteImport
      parentRoute: typeof PublicSignUpRoute
    }
    '/_public/sign-in/$': {
      id: '/_public/sign-in/$'
      path: '/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof PublicSignInSplatRouteImport
      parentRoute: typeof PublicSignInRoute
    }
    '/_public/(legal)/terms': {
      id: '/_public/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PubliclegalTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(legal)/support': {
      id: '/_public/(legal)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PubliclegalSupportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(legal)/privacy': {
      id: '/_public/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PubliclegalPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/lists/$listId': {
      id: '/_protected/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ProtectedListsListIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedListsListIdRoute: typeof ProtectedListsListIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedListsListIdRoute: ProtectedListsListIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicSignInRouteChildren {
  PublicSignInSplatRoute: typeof PublicSignInSplatRoute
}

const PublicSignInRouteChildren: PublicSignInRouteChildren = {
  PublicSignInSplatRoute: PublicSignInSplatRoute,
}

const PublicSignInRouteWithChildren = PublicSignInRoute._addFileChildren(
  PublicSignInRouteChildren,
)

interface PublicSignUpRouteChildren {
  PublicSignUpSplatRoute: typeof PublicSignUpSplatRoute
}

const PublicSignUpRouteChildren: PublicSignUpRouteChildren = {
  PublicSignUpSplatRoute: PublicSignUpSplatRoute,
}

const PublicSignUpRouteWithChildren = PublicSignUpRoute._addFileChildren(
  PublicSignUpRouteChildren,
)

interface PublicRouteChildren {
  PublicSignInRoute: typeof PublicSignInRouteWithChildren
  PublicSignUpRoute: typeof PublicSignUpRouteWithChildren
  PubliclegalPrivacyRoute: typeof PubliclegalPrivacyRoute
  PubliclegalSupportRoute: typeof PubliclegalSupportRoute
  PubliclegalTermsRoute: typeof PubliclegalTermsRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignInRoute: PublicSignInRouteWithChildren,
  PublicSignUpRoute: PublicSignUpRouteWithChildren,
  PubliclegalPrivacyRoute: PubliclegalPrivacyRoute,
  PubliclegalSupportRoute: PubliclegalSupportRoute,
  PubliclegalTermsRoute: PubliclegalTermsRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  SubscriptionRoute: SubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
