/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as ProtectedSubscriptionRouteImport } from './routes/_protected/subscription'
import { Route as ProtectedArchiveRouteImport } from './routes/_protected/archive'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PubliclegalTermsRouteImport } from './routes/_public/(legal)/terms'
import { Route as PubliclegalSupportRouteImport } from './routes/_public/(legal)/support'
import { Route as PubliclegalPrivacyRouteImport } from './routes/_public/(legal)/privacy'
import { Route as ProtectedListsListIdRouteImport } from './routes/_protected/lists.$listId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedSubscriptionRoute = ProtectedSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedArchiveRoute = ProtectedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliclegalTermsRoute = PubliclegalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PubliclegalSupportRoute = PubliclegalSupportRouteImport.update({
  id: '/(legal)/support',
  path: '/support',
  getParentRoute: () => PublicRoute,
} as any)
const PubliclegalPrivacyRoute = PubliclegalPrivacyRouteImport.update({
  id: '/(legal)/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedListsListIdRoute = ProtectedListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ProtectedArchiveRoute
  '/subscription': typeof ProtectedSubscriptionRoute
  '/sign-in': typeof PublicSignInRoute
  '/lists/$listId': typeof ProtectedListsListIdRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/support': typeof PubliclegalSupportRoute
  '/terms': typeof PubliclegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ProtectedArchiveRoute
  '/subscription': typeof ProtectedSubscriptionRoute
  '/sign-in': typeof PublicSignInRoute
  '/lists/$listId': typeof ProtectedListsListIdRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/support': typeof PubliclegalSupportRoute
  '/terms': typeof PubliclegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/archive': typeof ProtectedArchiveRoute
  '/_protected/subscription': typeof ProtectedSubscriptionRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_protected/lists/$listId': typeof ProtectedListsListIdRoute
  '/_public/(legal)/privacy': typeof PubliclegalPrivacyRoute
  '/_public/(legal)/support': typeof PubliclegalSupportRoute
  '/_public/(legal)/terms': typeof PubliclegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/subscription'
    | '/sign-in'
    | '/lists/$listId'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/subscription'
    | '/sign-in'
    | '/lists/$listId'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/archive'
    | '/_protected/subscription'
    | '/_public/sign-in'
    | '/_protected/lists/$listId'
    | '/_public/(legal)/privacy'
    | '/_public/(legal)/support'
    | '/_public/(legal)/terms'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/subscription': {
      id: '/_protected/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof ProtectedSubscriptionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/archive': {
      id: '/_protected/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ProtectedArchiveRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/(legal)/terms': {
      id: '/_public/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PubliclegalTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(legal)/support': {
      id: '/_public/(legal)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PubliclegalSupportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(legal)/privacy': {
      id: '/_public/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PubliclegalPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/lists/$listId': {
      id: '/_protected/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ProtectedListsListIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedArchiveRoute: typeof ProtectedArchiveRoute
  ProtectedSubscriptionRoute: typeof ProtectedSubscriptionRoute
  ProtectedListsListIdRoute: typeof ProtectedListsListIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedArchiveRoute: ProtectedArchiveRoute,
  ProtectedSubscriptionRoute: ProtectedSubscriptionRoute,
  ProtectedListsListIdRoute: ProtectedListsListIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicSignInRoute: typeof PublicSignInRoute
  PubliclegalPrivacyRoute: typeof PubliclegalPrivacyRoute
  PubliclegalSupportRoute: typeof PubliclegalSupportRoute
  PubliclegalTermsRoute: typeof PubliclegalTermsRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicSignInRoute: PublicSignInRoute,
  PubliclegalPrivacyRoute: PubliclegalPrivacyRoute,
  PubliclegalSupportRoute: PubliclegalSupportRoute,
  PubliclegalTermsRoute: PubliclegalTermsRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
