/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignUpRouteImport } from './routes/_public/sign-up'
import { Route as PublicSignInRouteImport } from './routes/_public/sign-in'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicRequestResetPasswordRouteImport } from './routes/_public/request-reset-password'
import { Route as Public2faRouteImport } from './routes/_public/2fa'
import { Route as ProtectedArchiveRouteImport } from './routes/_protected/archive'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PubliclegalTermsRouteImport } from './routes/_public/(legal)/terms'
import { Route as PubliclegalSupportRouteImport } from './routes/_public/(legal)/support'
import { Route as PubliclegalPrivacyRouteImport } from './routes/_public/(legal)/privacy'
import { Route as ProtectedListsListIdRouteImport } from './routes/_protected/lists.$listId'
import { Route as ProtectedHomeRouteImport } from './routes/_protected/home'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignUpRoute = PublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInRoute = PublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRequestResetPasswordRoute =
  PublicRequestResetPasswordRouteImport.update({
    id: '/request-reset-password',
    path: '/request-reset-password',
    getParentRoute: () => PublicRoute,
  } as any)
const Public2faRoute = Public2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedArchiveRoute = ProtectedArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliclegalTermsRoute = PubliclegalTermsRouteImport.update({
  id: '/(legal)/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PubliclegalSupportRoute = PubliclegalSupportRouteImport.update({
  id: '/(legal)/support',
  path: '/support',
  getParentRoute: () => PublicRoute,
} as any)
const PubliclegalPrivacyRoute = PubliclegalPrivacyRouteImport.update({
  id: '/(legal)/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedListsListIdRoute = ProtectedListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedHomeRoute = ProtectedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ProtectedArchiveRoute
  '/2fa': typeof Public2faRoute
  '/request-reset-password': typeof PublicRequestResetPasswordRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/lists/$listId': typeof ProtectedListsListIdRoute
  '/home': typeof ProtectedHomeRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/support': typeof PubliclegalSupportRoute
  '/terms': typeof PubliclegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ProtectedArchiveRoute
  '/2fa': typeof Public2faRoute
  '/request-reset-password': typeof PublicRequestResetPasswordRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/sign-in': typeof PublicSignInRoute
  '/sign-up': typeof PublicSignUpRoute
  '/lists/$listId': typeof ProtectedListsListIdRoute
  '/home': typeof ProtectedHomeRoute
  '/privacy': typeof PubliclegalPrivacyRoute
  '/support': typeof PubliclegalSupportRoute
  '/terms': typeof PubliclegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_protected/archive': typeof ProtectedArchiveRoute
  '/_public/2fa': typeof Public2faRoute
  '/_public/request-reset-password': typeof PublicRequestResetPasswordRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/sign-in': typeof PublicSignInRoute
  '/_public/sign-up': typeof PublicSignUpRoute
  '/_protected/lists/$listId': typeof ProtectedListsListIdRoute
  '/_protected/home': typeof ProtectedHomeRoute
  '/_public/(legal)/privacy': typeof PubliclegalPrivacyRoute
  '/_public/(legal)/support': typeof PubliclegalSupportRoute
  '/_public/(legal)/terms': typeof PubliclegalTermsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/2fa'
    | '/request-reset-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/lists/$listId'
    | '/home'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/2fa'
    | '/request-reset-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/lists/$listId'
    | '/home'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/_protected/archive'
    | '/_public/2fa'
    | '/_public/request-reset-password'
    | '/_public/reset-password'
    | '/_public/sign-in'
    | '/_public/sign-up'
    | '/_protected/lists/$listId'
    | '/_protected/home'
    | '/_public/(legal)/privacy'
    | '/_public/(legal)/support'
    | '/_public/(legal)/terms'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/sign-up': {
      id: '/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof PublicSignUpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in': {
      id: '/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof PublicSignInRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/request-reset-password': {
      id: '/_public/request-reset-password'
      path: '/request-reset-password'
      fullPath: '/request-reset-password'
      preLoaderRoute: typeof PublicRequestResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/2fa': {
      id: '/_public/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof Public2faRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/archive': {
      id: '/_protected/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ProtectedArchiveRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/(legal)/terms': {
      id: '/_public/(legal)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PubliclegalTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(legal)/support': {
      id: '/_public/(legal)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof PubliclegalSupportRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(legal)/privacy': {
      id: '/_public/(legal)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PubliclegalPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/lists/$listId': {
      id: '/_protected/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ProtectedListsListIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedArchiveRoute: typeof ProtectedArchiveRoute
  ProtectedListsListIdRoute: typeof ProtectedListsListIdRoute
  ProtectedHomeRoute: typeof ProtectedHomeRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedArchiveRoute: ProtectedArchiveRoute,
  ProtectedListsListIdRoute: ProtectedListsListIdRoute,
  ProtectedHomeRoute: ProtectedHomeRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  Public2faRoute: typeof Public2faRoute
  PublicRequestResetPasswordRoute: typeof PublicRequestResetPasswordRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSignInRoute: typeof PublicSignInRoute
  PublicSignUpRoute: typeof PublicSignUpRoute
  PubliclegalPrivacyRoute: typeof PubliclegalPrivacyRoute
  PubliclegalSupportRoute: typeof PubliclegalSupportRoute
  PubliclegalTermsRoute: typeof PubliclegalTermsRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  Public2faRoute: Public2faRoute,
  PublicRequestResetPasswordRoute: PublicRequestResetPasswordRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSignInRoute: PublicSignInRoute,
  PublicSignUpRoute: PublicSignUpRoute,
  PubliclegalPrivacyRoute: PubliclegalPrivacyRoute,
  PubliclegalSupportRoute: PubliclegalSupportRoute,
  PubliclegalTermsRoute: PubliclegalTermsRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
